version: '3'
services:
  box:
    container_name: box
    build: .
    restart: on-failure
    volumes:
      - .:/1
    working_dir: /1
    ports:
      - "8000:8000"
    command: sh -c "php composer.phar install && bin/console do:mi:mi -n && bin/console do:fi:lo -n && ./symfony server:start"
